### ISSUE TITLE
Возможный miscopy

### ISSUE THREAD

**Issue by zsavely** [TheDrHax/mosmetro-android#107]
Кажется, [данная строка](https://github.com/TheDrHax/mosmetro-android/blob/master/src/pw/thedrhax/mosmetro/activities/AboutActivity.java#L67) – лишняя. Есть ли особый смысл в вызове метода `executePendingTransactions()`?

**Comment by TheDrHax** [comment]
Действительно, в SettingsActivity этот вызов был нужен, так как сразу за ним производятся операции с фрагментом. А в AboutActivity никаких операций не требуется. Спасибо!
