### ISSUE TITLE
Проблема с вводом капчи

### ISSUE THREAD

**Issue by lgg** [TheDrHax/mosmetro-android#119]
Сколько раз вылезал запрос на капчу - вводил верно(я не робот, честно) - постоянно вылезал повторный запрос. Помогало только открыть в браузере любую ссылку по http, дождаться окна авторизации в wifi и там уже вводить капчу. 

Что следует сделать, предоставить для полной отчетности, для того случая, когда в следующий раз столкнусь с таким?

**Comment by TheDrHax** [comment]
А какая у вас сейчас версия установлена? Если я правильно помню, сборки master с 170 по 174 были сломаны в этом плане.

> Что следует сделать, предоставить для полной отчетности, для того случая, когда в следующий раз столкнусь с таким?

Может помочь лог подключения. Если не сложно, проигнорируйте запрос капчи из фона и откройте ручное подключение. Там должен появиться такой же запрос. При этом можно попробовать пару раз её ввести и сразу же отправить лог мне мне. Только как-нибудь в теме письма обозначьте, что тикет #119 или типа того :)

**Comment by lgg** [comment]
@TheDrHax хмм, может я совсем отстал от жизни и зря панику развожу?)

Ставил из google play, версия приложения 1.7.3-54

Про лог понял, спасибо большое. Столкнусь с такой ситуацией еще раз - обязательно отправлю.

**Comment by TheDrHax** [comment]
Хм, версия из Google Play только недавно вышла, так что для неё это явно не норма. У меня есть один способ воспроизвести эту ошибку, так что попробую сделать это. Я таким образом в прошлый раз проблему нашёл.

**Comment by TheDrHax** [comment]
Прежним методом ошибку воспроизвести не удалось. Похоже на серверной стороне ничего не изменилось. Я добавил немного сообщений в лог в ветке [debug](https://mosmetro.duckdns.org/api/v1/download.php?branch=debug), которые, возможно, помогут выявить проблему. Если не сложно, попробуйте её установить и отправить мне лог, когда снова не получится ввести капчу. Спасибо :)

**Comment by TheDrHax** [comment]
Ого, как быстро время летит. Закрою этот тикет, а то уже больше месяца прошло. Если проблема снова возникнет, то переоткройте его тогда.
