### ISSUE TITLE
Возможное изменение алгоритма в метро??

### ISSUE THREAD

**Issue by gargullia** [TheDrHax/mosmetro-android#134]
Захожу в метро, включаю wi-fi и подключилось к сети метро. Но интернета нет. Захожу в приложение, пишет что соединение есть, но на делу нету.
![screenshot_20170316-235905](https://cloud.githubusercontent.com/assets/19420334/24072626/f193c14c-0bfa-11e7-942e-7b735698d6ad.png)
![screenshot_20170316-235910](https://cloud.githubusercontent.com/assets/19420334/24072627/f193ef50-0bfa-11e7-87a0-9e275f1a0d6e.png)
Идет проверка..
![screenshot_20170317-005603](https://cloud.githubusercontent.com/assets/19420334/24072641/1d309bcc-0bfb-11e7-9d3a-183d61f6c247.png)
[pw.thedrhax.mosmetro.txt](https://github.com/TheDrHax/mosmetro-android/files/852475/pw.thedrhax.mosmetro.txt)
[pw.thedrhax.mosmetro.txt](https://github.com/TheDrHax/mosmetro-android/files/852476/pw.thedrhax.mosmetro.txt)
Приложил лог. Подключиться не удалось, смотрел рекламу

**Comment by TheDrHax** [comment]
Не похоже на изменение алгоритма. Тут, скорее всего, дело в несовершенной проверке наличия доступа в интернет. Она иногда всё ещё выдаёт неправильный результат. В данный момент эта проблема имеет максимальный приоритет.

Обычно изменение алгоритма проявляется в куда больших масштабах чем просто "Уже подключено".
