### ISSUE TITLE
Будут ли шоркаты для андроид 7

### ISSUE THREAD

**Issue by gargullia** [TheDrHax/mosmetro-android#137]

**Comment by TheDrHax** [comment]
Они уже есть. Их можно создать из окна ручного подключения или через стандартное меню с виджетами. Переоткройте, если я вас неправильно понял.

**Comment by gargullia** [comment]
@TheDrHax Я имел ввиду по долгому удержанию на иконке 
![maps](https://cloud.githubusercontent.com/assets/19420334/25134421/30d630c2-2458-11e7-89c2-bfd4a17872dd.jpg)
