### ISSUE TITLE
Повторная проверка

### ISSUE THREAD

**Issue by rshadow** [TheDrHax/mosmetro-android#141]
Очень часто происходит такая ситуация что подключается все удачно. Можно открывать браузер и сразу пользоваться интернетом.
Но через несколько станций, если попытаться зайти на сайт, опять начинаются какие то редиректы и попадаешь на wifi.ru. Как будто сети разные и проверка делается заново.

Можно как то мониторить повторную проверку и пропускать заход на wifi.ru?

Xiaomi Redmi 4 Pro
1.7.5-57

**Comment by TheDrHax** [comment]
Об этой проблеме уже известно (#135), только вот никак не доберусь =\

**Comment by rshadow** [comment]
Спасибо за ответ. Буду ждать.
