### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by dimqua** [TheDrHax/mosmetro-android#143]
Не возражает ли разработчик против размещения приложения на f-droid?

**Comment by TheDrHax** [comment]
@dimqua Я не против. Просто сейчас у меня даже на разработку времени не особо хватает, а так же уже есть 3 вектора распространения (GitHub, Google Play и встроенные обновления). Если Вы это сделаете, то было бы неплохо :)

**Comment by dimqua** [comment]
https://gitlab.com/fdroid/rfp/issues/149

**Comment by dimqua** [comment]
[![](https://camo.githubusercontent.com/f9574a79e3fe61202392c44e55f0bdab261a9561/68747470733a2f2f662d64726f69642e6f72672f62616467652f6765742d69742d6f6e2e706e67)](https://f-droid.org/repository/browse/?fdid=pw.thedrhax.mosmetro)
