### ISSUE TITLE
Удаление mosmetro v1

### ISSUE THREAD

**Issue by substanceof** [TheDrHax/mosmetro-android#147]
Домен login.wi-fi.ru разделегировали, так что, я думаю, стоит перестать использовать его как вариант обхода капчи в v2. 

```
drill login.wi-fi.ru @8.8.8.8
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 11676
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL
 0
;; QUESTION SECTION:
;; login.wi-fi.ru.      IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:
wi-fi.ru.       1799    IN      SOA     ns1.reg.ru. hostmaster.ns1
reg.ru. 1495207846 14400 3600 604800 10800

;; ADDITIONAL SECTION:

;; Query time: 95 msec
;; SERVER: 8.8.8.8
```

**Comment by TheDrHax** [comment]
@substanceof Так вот, почему обход капчи работать перестал! Спасибо за информацию!

Хотел попробовать обратиться по IP с подменой заголовка Host. Сервер выдаёт перенаправление на login.wi-fi.ru/am/, но дальше только ошибка 502. Похоже, сервер уже свернули...

**Comment by substanceof** [comment]
Я раньше руками авторизировался там, благо, без скриптов не было рекламы. После того, как перестало рабоиать, собственно, и перешел на это приложение

**Comment by TheDrHax** [comment]
Пока что так. Старый алгоритм пока не помешает, а вот неработающие методы обхода очень долго могут отрабатывать без какого-либо эффекта. Возможно, MosMetroV1 ещё вернётся :)
