### ISSUE TITLE
Сеть AURA 

### ISSUE THREAD

**Issue by rlex** [TheDrHax/mosmetro-android#36]
В метро появилась новая сеть. Что это именно - не знаю, но работает на частоте 5 ггц и выдает тот же captive портал c той же метрошной авторизацией.
Но никаких официальных новостей не было. 
Может стоит добавить в список SSIDов?

**Comment by TheDrHax** [comment]
Поддержка этой сети была добавлена в коммите https://github.com/TheDrHax/mosmetro-android/commit/cbf4f49527bd309e87d997a84679fed49689bd6b и попала в версию 1.6-29, которая, пока что, в бете Google Play, потому что в ней осталось несколько косяков, которые нужно доработать (в основном, в интерфейсе).

Вы можете присоединиться к [тестированию в Google Play](https://play.google.com/apps/testing/pw.thedrhax.mosmetro), либо включить ветку обновления master  в настройках приложения, чтобы получить актуальную версию.

**Comment by TheDrHax** [comment]
Версия 1.6-31 с поддержкой сети AURA (только в пределах метро) стала публичной. 46b071ae03aeb4c479bd78190eaba318636a0e47
