### ISSUE TITLE
Android возвращает некорректное название сети

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#41]
В некоторых случаях приложение не может определить корректное название сети Wi-Fi, чтобы подобрать правильный алгоритм.

Вот пример лога, появившегося при подключении к сети MosMetro_Free:
```
> 15 апр 2016 г. 1:17:59 PM
>> Определение названия сети
>> Поиск подходящего алгоритма для сети "orBfQcNFF06CIzo"
<< Ошибка: Вы не подключены ни к одной из поддерживаемых сетей
```

**Comment by TheDrHax** [comment]
Дополнение от того же пользователя: Строка "orBfQcNFF06CIzo" выводится для всех протестированных сетей, т.е. она не является другим представлением названия сети. Похоже, это проблема в реализации Chooser в Authenticator.

**Comment by TheDrHax** [comment]
У другого пользователя проблема решилась переустановкой приложения. Не уведен, что это решение имеет отношение к данной проблеме, так как у него не была установлена сборка с расширенным логом.

**Comment by TheDrHax** [comment]
У того пользователя приложение не работало и раньше (а именно, автоматическое подключение). Скорее всего, это какая-то защита SSID со стороны системы. Не совсем ясна причина такого поведения, но, похоже, придется искать альтернативный способ определения SSID.

**Comment by Revertron** [comment]
А у меня если телефон недоподключился к сети показывает 0x. Я думаю, что это парсинг такой, с задержкой парсит название сети. А та строка, или в моём случае 0x - это значение по умолчанию.

**Comment by TheDrHax** [comment]
Скорее всего, проблема в кривой прошивке устройства. Она проявляется очень редко, так что исправление этой проблемы не стоит затрачиваемых усилий.

**Comment by TheDrHax** [comment]
'''
> 14.09.2016 9:07:49
>> Определение названия сети
>> Поиск подходящего алгоритма для сети Tele2_8F1D18
<< Ошибка: Вы не подключены ни к одной из поддерживаемых сетей
'''

Новое сообщение... Похоже, что на некоторых устройствах вместо SSID возвращается что-то связанное с мобильной сетью. Т.е. в таких системах нет особой разницы, подключен Wi-Fi или нет.
