### ISSUE TITLE
Повторение отправки некоторых запросов вместо перезапуска всего алгоритма

### ISSUE THREAD

**Issue by Revertron** [TheDrHax/mosmetro-android#47]
Вместо обработки android.net.wifi.STATE_CHANGE лучше ловить android.net.wifi.WIFI_STATE_CHANGED (WifiManager.WIFI_STATE_CHANGED_ACTION).

Дело в том, что сейчас Receiver получает событие задолго до реального подключения, и приходится гадать (кто на чём может) для установки правильной задержки перед получением IP.
Но задержка не нужна при получении android.net.wifi.WIFI_STATE_CHANGED. Там нужно только проверить, что сеть действительно подключилась, а не сделала что-то другое и всё.

Сейчас посмотрю код, может PR запилю.

**Comment by TheDrHax** [comment]
Полезная информация, спасибо! Давно пора разобраться с классами ConnectionService и NetworkReceiver. Можно будет тогда убрать задержку, которая у некоторых почему-то зависает.

**Comment by Revertron** [comment]
Ну, задержка реально существует как костыль, чтобы отсрочить попытки подключения. Но ведь проблема именно в том, что броадкаст не тот слушается :)
Я собрал себе новый вариант, поезжу и посмотрю как он будет работать. Может совместно причешем функционал :)

**Comment by Revertron** [comment]
Задержка, оказывается, всё равно нужна, но по другой причине. Событие о подключении приходит на секунду-две раньше, чем WifiManager может дать настоящий SSID.
Я сейчас еще запилил более правильный вариант обработки подключения с запуском отдельного потока, который подождет SSID и запустит сервис.

**Comment by Revertron** [comment]
Оокей, я натестировался вдоль и поперёк. Изначальное моё предложение оказалось неправильным, признаю ошибку.
Но сейчас я написал хороший вариант, который надо хорошо протестировать. Протестирую - отпишусь.

**Comment by TheDrHax** [comment]
Нет ли у вас планов вынести работу на GitHub, чтобы я тоже присоединился к тестированию?

Я тут подумал найти какой-нибудь фреймворк, в котором уже предусмотрена большая часть проблем с сетью, чтобы самим костыли не строить. Например, [pwittchen/ReactiveNetwork](https://github.com/pwittchen/ReactiveNetwork) выглядит интересным, но, похоже, не решит проблему с названием Wi-Fi (#41).

**Comment by Revertron** [comment]
Я планирую привести свой подход к тому, что есть сейчас и запилить патч-реквест. Но изменений несколько:
1. Слушаем тот же `android.net.wifi.STATE_CHANGE`, но проверяем состояние сети при получении броадкаста:
```
final boolean prefConnectOnCaptivePortalCheck = settings.getBoolean("pref_connect_on_captive_portal_check", false);
final int threadCount = Integer.parseInt(settings.getString("pref_thread_count", "2"));

if (settings.getBoolean("pref_autoconnect", true)) {
    Log.d(TAG, "Action: " + intent.getAction());

    final String ssid = intent.getStringExtra(WifiManager.EXTRA_BSSID);
    NetworkInfo info = intent.getParcelableExtra(WifiManager.EXTRA_NETWORK_INFO);
    Log.d(TAG, "SSID: " + ssid + " NetworkInfo: " + info.toString());
    if (ssid != null && info != null) {
        if (info.getState() == NetworkInfo.State.CONNECTING && info.getDetailedState() == NetworkInfo.DetailedState.CAPTIVE_PORTAL_CHECK) {
            Log.d(TAG, "Android is checking for captive portal...");
            if (prefConnectOnCaptivePortalCheck) {
                startRunnables(threadCount);
            }
        }
        if (info.getState() == NetworkInfo.State.CONNECTED) {
            Log.d(TAG, "Connected to Wi-Fi");
            if (!prefConnectOnCaptivePortalCheck) {
                startRunnables(threadCount);
            }
        }
    }
}
```
2. Кроме того, как видно из кода, я сделал настройку подключения в несколько потоков сразу - `pref_thread_count`. Как показывают тесты, намного лучше получается подключиться в час пик.
3. Еще один момент - у Firefox есть хитрость, которую они используют чтобы быстрее отсылать данные по вайфаю. Если девайс подключен к вайфаю, они при отсылке любых данных ещё кидают кучу рандомных UDP пакетов на роутер чтобы добить wi-fi frame до его размера.

**Comment by Revertron** [comment]
А насчет фреймворков - я не думаю, что это вообще нужно.

**Comment by TheDrHax** [comment]
Звучит замечательно, спасибо вам! Не задумывался о многопоточном подключении. Буду ждать PR тогда.

**Comment by Revertron** [comment]
Сложность теперь в том, что я сделал для теста всё в самом классе ресивере, а теперь надо как-то перенести эту логику в сервис...

**Comment by TheDrHax** [comment]
Насколько я вижу по этому куску кода, в NetworkReceiver всё завязано на тот Intent, который он получает от системы. От него можно взять все данные и передать в ConnectionService, если сделать, например, так:
```
Intent service = new Intent(context, ConnectionService.class);
service.putExtras(intent);

if (settings.getBoolean("pref_autoconnect", true))
   context.startService(new Intent(context, ConnectionService.class));
```

После этого весь код из NetworkReceiver можно вставить в метод onHandleIntent() в ConnectionService. Если, конечно, я всё правильно понял. Просто метода startRunnables у меня нет.

**Comment by Revertron** [comment]
Вот вся соль именно в том методе, который стартует раннаблы, по числу потоков с секундной задержкой между стартами.
Я чуть позже попробую разрулить и добавить всё в сервис.

**Comment by Revertron** [comment]
Короче, вот архивчик с моим вариантом подключения, может вместе придумаем как его встроить в текущий код:
https://cloud.jamm.me/index.php/s/4XieHSUvSL9I9I5
Можете найти меня по такому же нику в Телеграм, обсудим.

**Comment by TheDrHax** [comment]
Из того, что удалось сделать с телефона:
* после распаковки Git немного сошел с ума (некритично, но потребует исправления через компьютер)
![screenshot_20160607-104902 01](https://cloud.githubusercontent.com/assets/6968908/15850073/b4c614e0-2c9e-11e6-82b6-44f6a03b3452.png)
* WifiReceiver, почему-то, не запускается. Никакой реакции ни на MosMetro_Free, ни на AURA. Пробовал изменять настройки, но, похоже, до них процесс не доходит.

Пока что компьютера под рукой нет, так что больше сказать не могу.

А насчет многопоточности: нам же просто нужно отправлять запросы в несколько потоков? Может тогда спустить управление потоками на уровень Authenticator'а или даже MosMetro? Т.е. чтобы вышестоящие классы об этом даже не подозревали. Просто неизвестно, как поведет себя многопоточность, например, с MosGorTrans, который я собираюсь когда-нибудь доделать.

**Comment by Revertron** [comment]
WifiReceiver я еще добавил в манифест, закомментарив NetworkReceiver, чтобы не мешался при тестах.
Насчет спуска в MosMetro я как раз тоже думал. Чтобы сервис снаружи даже об этом не догадывался.

**Comment by TheDrHax** [comment]
Кстати, можно пойти дальше: распараллелить каждый отдельный запрос. Нам же нужно просто больше забить канал для получения приоритета? Сделать, например, чтобы каждый запрос отправлялся несколько раз, а успешный ответ передавался дальше. На таком уровне получится уведомления о прогрессе сохранить. Только такой подход будет работать не для каждого запроса, поэтому можно сделать отдельный метод. Благо, абстрактный клиент есть уже.

P.S. Может стоит переименовать этот тикет во что-то связанное с многопоточностью, раз уж другой Intent себя не оправдал? А использование полей из Intent для определения сети перенести в другой тикет, чтобы логически его отделить.

**Comment by Revertron** [comment]
Вот, кстати, мне нравятся ваши предложения :)

**Comment by TheDrHax** [comment]
Вроде, нормально работает, так что закрываю этот тикет. Для многопоточности можно будет еще один потом создать.
