### ISSUE TITLE
Вынести строки из кода в strings.xml для возможности локализации

### ISSUE THREAD

**Issue by Revertron** [TheDrHax/mosmetro-android#48]
Лучше вынести строки в strings.xml, чтобы можно было предоставить желающим возможность перевода программы. Да и сейчас текст в коде считается моветоном.
Эта задача не так страшна, тем более, что IDEA предоставляет для этого отличную автоматизацию.

**Comment by TheDrHax** [comment]
Спасибо за совет! Давно хотел это сделать, но всё руки не доходили. То, что сейчас находится в strings.xml, попало туда как раз из-за предупреждений IDEA. Как будет время, займусь.

**Comment by TheDrHax** [comment]
Вроде, ничего не пропустил. После небольшого тестирования перенесу в master.
