### ISSUE TITLE
Не говорить «уже подключено» при мобильном интернете

### ISSUE THREAD

**Issue by Nashev** [TheDrHax/mosmetro-android#49]
А то он в тоннеле плохо ловит, а эта программа не начинает подключаться к MosMetro_Free

**Comment by TheDrHax** [comment]
@Nashev Это довольно нетривиальная задача, так как даже если все запросы уходят через мобильную сеть, Android продолжает сообщать о том, что устройство подключено к Wi-Fi до последнего (а иногда и еще дольше).

Попробую еще поискать способ этого избежать, но не знаю, возможно ли это. Всё-таки сеть в Android довольно странно работает. Наверно, стоит какой-то фреймворк использовать.

В issue #47, например, похожая проблема. Там Android неправильно сообщает о подключении: сигнал приходит раньше, чем надо.

**Comment by Nashev** [comment]
А узнать имя текущей WiFi-сети возможности не дают?

**Comment by Nashev** [comment]
Кстати, кажись эта беда настала при последнем обновлении.

**Comment by TheDrHax** [comment]
Дело как раз в том, что Android сообщает, что подключен именно к нужной сети, но при этом запросы пускает по мобильной. Такая проблема, скорее всего, была и раньше, но я не мог её воспроизвести, так как у меня мобильная сеть не ловит в метро. Уже подыскиваю какую-нибудь библиотеку для работы с сетью, но они по большей части делают то же, что и я.

У меня такая же проблема была при тестировании сборок для mosgortrans: приложение думало, что уже подключено, так как сеть не успела до конца соединиться. Решить эту проблему удалось только настроив Android через Профили (встроенная функция в Cyanogen OS) на отключение мобильных данных при подключении к определенным сетям.

Есть еще тривиальное решение: если приложение смогло подключиться к интернету, то нужно просто [определить название провайдера](https://wtfismyip.com/json) и сравнить его с эталонным. Но такое решение может породить несколько точек отказа, что постоянно приводит к проблемам у других пользователей.

**Comment by TheDrHax** [comment]
Возможное решение: http://stackoverflow.com/questions/28592600/multi-networking-in-lollipop/28664841#28664841

**Comment by TheDrHax** [comment]
Не знаю, сработает это или нет. Если что, переоткройте этот тикет, будем дальше разбираться. Очень уж баг случайный и редкий для меня.
