### ISSUE TITLE
Не подключается с первого (и даже с третьего) раза

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#50]
В последнее время стала очень выражена проблема, когда приложение тратит все попытки подключения, однако каждый раз доступ в интернет не появляется.

Нормальное подключение должно занимать 1-2 попытки из 3 (по умолчанию), однако на данный момент не всегда хватает даже 5 попыток.

Типичное проявление этой проблемы: в конце каждой попытки появляется ошибка "доступ в интернет отсутствует", т.е. сеть продолжает перенаправлять устройство на авторизацию.

Стоит заметить, что подключение через браузер всегда срабатывает с первого раза. Точно так же может сработать и ручное подключение, если запустить его где-то через минуту после получения IP (не точно).

Предположительные причины проблемы:
* в сеть добавили ограничение скорости подключения для отсеивания скриптов авторизации: приложение отсылает запрос сразу после получения IP;
* некритично поменялся алгоритм подключения: стоит сравнить дамп подключения через браузер с тем, что в коде.

**Comment by TheDrHax** [comment]
Что удивительно, задержка в 10 секунд после получения IP адреса действительно помогла и подключение в большинстве случаев происходит с первого раза.

Либо в сети действительно появилось ограничение скорости авторизации, либо устройству не достаточно просто получить IP для общения с сервером.

Повторная попытка понадобилась только в случае, когда устройство неправильно подключилось к сети (ошибка "сеть недоствпна или не отвечает"). Первая попытка перезапустила Wi-Fi, а вторая нормально подключилась.

TODO:
* протестировать подключение более тщательно
* попробовать меньшую задержку (где-то 5 секунд)

**Comment by Revertron** [comment]
Очень похоже на связь с загруженностью состава. Я регулярно моментально подключаюсь к подходящим пустым поездам на станциях, но очень туго приходится в переполненном вагоне.
Я вижу очень точную корреляцию между загруженностью и ошибками подключения.

Надо, кстати, попробовать посмотреть программкой WiFi Analyzer на каких каналах висят точки. Мне кажется, они могут все (в разных вагонах) висеть на одном канале и мешать друг-другу. Чем больше устройств - тем больше собственных помех.

**Comment by TheDrHax** [comment]
@Revertron Странно то, что при добавлении задержки в 10 секунд перед первым подключением всё обычно проходит нормально. А еще, что удивительно, при этой ощибке весь алгоритм проходит нормально, т.е. сервер отвечает как и ожидалось, однако в конце интернет не появляется. Обычно при перегрузках либо сервер не отвечает, либо вообще пакеты не проходят, а тут на какую-то защиту похоже.

**Comment by Revertron** [comment]
Но у меня при многопоточном подключении сё нормально получается при малом количестве людей, а при забитом вагоне очень туго идет и не с первого раза. Чаще всего вообще ничего не идет и отваливается вайфай.

**Comment by TheDrHax** [comment]
Похоже, задержка в 5 секунд действительно помогает. Стабильность соединения стала гораздо выше, если не ломиться в сеть сразу.
