### ISSUE TITLE
Сеть отключена. Повторите вход.

### ISSUE THREAD

**Issue by din235** [TheDrHax/mosmetro-android#53]
Здравствуйте, уважаемые разработчики. На моем Galaxy S5 возникает проблема: Включаешь Wi-Fi,  телефон сам находит сеть, подключается и вылетает с ошибкой "Сеть отключена...". Приходится принудительно заходить в настройки Wi-Fi,  принудительно подключаться, открывается браузер параллельно приложению, после чего у приложения остается всего 1 попытка из 3. Можно ли как-то поставить приложение в приоритет при подключении, вместо браузера (в качестве redirect-а)?  
В приложении, при этом, написано:
Ошибка: сеть недоступна или не отвечает. 
Перезапуск Wi-Fi. ..
И все, можно ждать до бесконечности.

P.S. Заранее прошу прощения, если этот вопрос не в Вашей компетенции.

**Comment by TheDrHax** [comment]
От автоматического отключения от сети может спасти "Переподключение к Wi-Fi" в настройках приложения, если я правильно понял проблему. Я этот пункт добавил как раз из-за такой излишней самостоятельности Android. При отключении от сети приложение будет добавлять её в очередь на подключение, чтобы не нужно было каждый раз это делать в настройках.

Еще более радикально можно избавиться от этой проблемы, если есть права root: [Отключение Captive Portal](https://github.com/TheDrHax/mosmetro-android/wiki#%D0%9E%D1%82%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-captive-portal). В этом случае система будет относиться в сети как к обычному Wi-Fi, поэтому не должна будет открывать браузер и показывать уведомления.

> Можно ли как-то поставить приложение в приоритет при подключении, вместо браузера (в качестве redirect-а)?

Такое уже делалось в [одной из предыдущих версий](https://github.com/TheDrHax/mosmetro-android/commit/30a507a8f60ed786ce487843dc8c6375f971b8cb), однако потом адрес Captive Portal изменился и я решил отключить эту функцию. Могу добавить обратно, если получится это протестировать.
