### ISSUE TITLE
При добавлении нового события в лог подключения оно прокручивается на начало.

### ISSUE THREAD

**Issue by abonec** [TheDrHax/mosmetro-android#59]
Версия 1.6.2-37 - в логе подключения при каждом новом добавлении события, прокрутка улетает в начало, а не в конец, как это было сделано раньше. Смотреть что происходит очень неудобно.
В версии 1.6.1-34 работает как надо

**Comment by TheDrHax** [comment]
Протестировал в эмуляторе: баг проявляется в обеих версиях, но только если включено отображение подробных сообщений. Попробую разобраться.
