### ISSUE TITLE
Обработка каптчи для MosMetro v2

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#69]
Сразу после последнего обновления алгоритма MosMetro v2 #68 было замечено, что сеть как-то начала определять наличие автоматизаторов и теперь заставляет вводить каптчу.

Варианты решения:
* Обойти детектирование путём маскировки под браузер;
* Выводить каптчу в диалоговом окне в обход браузера;

![Авторизация](https://cloud.githubusercontent.com/assets/6968908/20528491/7041d00c-b0dd-11e6-9a0f-4c0ad784cf7c.jpg)

```html
<!-- код страницы авторизации -->
<html>
<head>
  <meta content="width=device-width, initial-scale=1.0, user-scalable=no" name="viewport">
  <link rel="stylesheet" media="screen" href="/assets/auth/application-e3916cabeea27bc11432f3c5ba9c3bf453b8a36ea296aa5ba7d85b90221b32f4.css">
</head>
<body>
  <div class="branding-header" style="z-index: 5 !important">
   <a class="header-item" href="http://login.wi-fi.ru/docs/offers/offer_auth.pdf">
    <div class="branding-header__offer">
     Нажимая кнопку «Войти в Интернет», вы принимаете условия оферты
    </div></a>
   <a class="header-item" href="http://login.wi-fi.ru/vmetro/faq?lang=ru&amp;client_mac=">
    <div class="branding-header__support">
     Поддержка
    </div></a>
   <a class="header-item" href="/auto_auth">
    <div class="branding-header__lang english">
     English
    </div></a>
  </div>
  <div class="auto-auth-view">
   <div class="content">
    <div class="message">
     Уважаемый пользователь.
     <br>Возможно, на Вашем устройстве установлено программное обеспечение, производящее автоматическую авторизацию, что противоречит «Условиям пользования Услугами». Для доступа к сети Интернет Вам необходимо удалить данную программу или внести корректировки в настройки браузера. Для автоматического подключения и доступа к сети Интернет без просмотра рекламы Вы можете подключить Услугу&nbsp;
     <a href="//login.wi-fi.ru/am/UI/Login?org=mac&amp;service=seamless&amp;goto=https://pay.wi-fi.ru">«Как&nbsp;дома»</a>.
    </div>
   </div>
   <form class="captcha__container" action="/auto_auth" accept-charset="UTF-8" method="post">
    <input name="utf8" type="hidden" value="✓">
    <input type="hidden" name="authenticity_token" value="er+y2sW/RmP2IJARGSWz6bgzjLAZm+vA+4yConIQ1VTyYi3fptevz6Vkj4tt5TJ4WnRz1LqhWsaW8nblpi90ZQ==">
    <img class="captcha__image" alt="Captcha" src="/rucaptcha/">
    <div class="captcha__controls">
     <input class="captcha__input form-control" placeholder="Введите текст с картинки" name="_rucaptcha" type="text" autocorrect="off" autocapitalize="off" pattern="[0-9a-z]*" maxlength="4" autocomplete="off">
     <input type="submit" name="commit" value="OK" class="captcha__submit" data-disable-with="OK">
    </div>
   </form>
  </div>
</body>
</html>
```

**Comment by BioQwer** [comment]
Еще не встречал, но картинка выглядит простой имеет смысл попытаться расшифровать картинку?

**Comment by stek29** [comment]
@BigQwer вот архив с почти четырьмя тысячами каптч, если вдруг понадобятся для тестирования.
http://rgho.st/6y4BFhCBd

**Comment by TheDrHax** [comment]
@BioQwer Я, конечно, не знаком с распознаванием символов, но мне кажется, что гораздо проще будет просто избегать её появления. Только я тоже ещё не сталкивался с ней, чтобы методы протестировать.

К тому же никто не мешает им в будущем усложнить эту каптчу, если мы научимся её распознавать.

**Comment by alexeyknyshev** [comment]
В итоге, вариант с автоматизированным разгадыванием капчи вы не рассматриваете?

> К тому же никто не мешает им в будущем усложнить эту каптчу, если мы научимся её распознавать.

Никто не мешает заставлять разгадывать капчу в любом случае, вне зависимости от того, задетектили ли нас как автоматизатора или нет

**Comment by TheDrHax** [comment]
@alexeyknyshev Мешает мнение непричастных пользователей :)

Всё-таки это непростая задача, в которой я не имею никакого опыта. Если сможете сделать, то я, конечно же, добавлю эту функцию в приложение. Просто мне кажется, что они не станут вводить капчу для всех, а проверку мы уже, вроде как, обошли (в ветке ua-test).
