### ISSUE TITLE
Android Doze whitelisting

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#86]
В новых версиях Android (вообще, с 6.0, но у меня с 7.1) было добавлено агрессивное энергосбережение, которое может превзойти даже MiUI. Благо, для нас оставили возможность запросить у пользователя разрешение на добавление в белый список.

Возможное решение: http://stackoverflow.com/a/32627788

**Comment by TheDrHax** [comment]
Проблему можно легко воспроизвести на месте, включив агрессивное энергосбережение и переключив настройку автоматической авторизации туда-обратно. В этом случае уведомление о подключении зависнет на 0%.

**Comment by TheDrHax** [comment]
Похоже, что добавление в белый список нарушает правила Google Play, что создаёт угрозу для всего проекта. Всё, что мы можем сделать — попросить пользователя самостоятельно отключить экономию энергии в настройках.

**Comment by ilabdsf** [comment]
> Похоже, что добавление в белый список нарушает правила Google Play

Есть список [acceptable use cases](https://developer.android.com/training/monitoring-device-state/doze-standby.html#whitelisting-cases), под "task automation app" подходит все что угодно вообще.

**Comment by TheDrHax** [comment]
Видел ту таблицу, на неё IDEA сразу ссылается, как только пытаешься реализовать запрос разрешения у пользователя. В таких делах следует проявлять двойную осторожность, так как Google выносит приложения за один шаг не в ту сторону. Под [этим ответом](http://stackoverflow.com/a/32424117) есть один комментарий:
> Be careful with ignoring battery optimizations - my app just got suspended from Google Play without prior notice for requesting REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, even though exempting the app from battery optimizations is crucial to my app's function, and I can't use GCM for technical reasons.

Хотя возможно, что в том случае приложение не вписывалось в task automation, в отличие от нашего, которое идеально туда подходит. "Technical reasons" могли заключаться в банальном нежелании переходить на GCM.
