### ISSUE TITLE
Лицензия

### ISSUE THREAD

**Issue by ilabdsf** [TheDrHax/mosmetro-android#92]
У приложения не указана лицензия кроме файла LICENSE с копией GPLv2. Зависимости json-simple и OkHttp распространяются под Apache 2.0, которая не совместима с GPLv2:
https://www.gnu.org/licenses/license-list.html#apache2
https://www.apache.org/licenses/GPL-compatibility.html

Нужно либо GPLv3 сделать с указанием в исходниках GPLv3 or any other later version, либо ISC/MIT/UNLICENSE.

В текущем виде приложение не получится залить, например, на F-Droid.

**Comment by TheDrHax** [comment]
@ilabdsf Спасибо за замечание! Судя по [сравнению](http://choosealicense.com/licenses/) лицензий, GPL является единственной, принуждающей открывать будущие форки и другие проекты, основанные на этом. Скорее всего, самым правильным решением будет переключиться на GPLv3, так как она при этом ещё и совместима с Apache 2.0. Не то, чтобы я очень защищал исходный код, но будет немного обидно, если кто-то будет улучшать проект, не выкладывая наработки также, как это делаю я.

Кстати, я так понимаю, файла LICENSE недостаточно, чтобы распространить лицензию на весь проект? Т.е. нужно её указывать также и в заголовке каждого файла с исходным кодом?

**Comment by ilabdsf** [comment]
> Кстати, я так понимаю, файла LICENSE недостаточно, чтобы распространить лицензию на весь проект? Т.е. нужно её указывать также и в заголовке каждого файла с исходным кодом?

По ссылке https://www.gnu.org/licenses/gpl.html есть раздел "How to Apply These Terms to Your New Programs". Писать можно и не в исходнике, но тогда нужно как-то явно указать, на какие файлы это распространяется. Самый простой способ просто в шапку добавить, как рекомендуется. Файл LICENSE нужен только для удобства, чтобы долго не искать полный текст лицензии. В случае GPLv3 он нужен для соответствия пункту "4. Conveying Verbatim Copies.":
> You may convey verbatim copies of the Program's source code ... provided that you ... give all recipients a copy of this License along with the Program.

> Судя по сравнению лицензий, GPL является единственной, принуждающей открывать будущие форки и другие проекты, основанные на этом.

На самом деле еще MPL.

> Скорее всего, самым правильным решением будет переключиться на GPLv3, так как она при этом ещё и совместима с Apache 2.0. Не то, чтобы я очень защищал исходный код, но будет немного обидно, если кто-то будет улучшать проект, не выкладывая наработки также, как это делаю я.

Я бы также сделал. В случае проблем с совместимостью с какими-нибудь библиотеками лицензию всегда можно и поменять.

**Comment by TheDrHax** [comment]
@ilabdsf Спасибо, стало намного понятнее. Последний раз я занимался этим вопросом ещё в момент создания репозитория на GitHub (ещё до подключения сторонних библиотек). Отредактирую файлы, как только время появится.

**Comment by TheDrHax** [comment]
Всё ли теперь в порядке? Думаю, файлы ресурсов под эту лицензию не нужно помещать (да и не видел ничего подобного до этого).

**Comment by ilabdsf** [comment]
Да, все ок.
