### ISSUE TITLE
Реализовать постоянный фоновый процесс

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#94]
Так как особых улучшений на устройствах с MiUI и другими глючными оболочками не предвидится, а отрицательных отзывов от таких пользователей в последнее время всё больше (обладатели Xiaomi — самые активные комментаторы в Google Play), нужно реализовать фоновый процесс, который будет закрепляться в памяти при загрузке устройства или при открытии приложения.

* Чтобы исключить убийство этого процесса при нехватке памяти, нужно закрепить его через постоянное уведомление ([startForeground](https://developer.android.com/guide/components/services.html#Foreground)).

* Фоновый процесс должен отслеживать сеть через WifiUtils и/или отлавливать Broadcast Intent с состоянием Wi-Fi через динамический Receiver.

* Эта функция должна быть полностью опциональной. Включаться по умолчанию она должна только на устройствах Xiaomi.

Связанное обсуждение: #58.

**Comment by zsavely** [comment]
На некоторых прошивках Lenovo, кстати, тоже ничего не происходит. Так что `startForeground()` нужен на Lenovo тоже.

**Comment by TheDrHax** [comment]
Проблема реагирования на события Wi-Fi всё ещё актуальна, но ConnectionService теперь закреплён через startForeground().
